name: Publish npm package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/
          scope: '@wdesgardin'
      - run: yarn
      - run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn docs
      - name: publish doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CI_GH_PAGES }}
          publish_dir: ./docs
